"""
编码前门禁 — 强制完成技术栈预研后才能开始编码。
"""

from __future__ import annotations

from pathlib import Path


class PreCodeGate:
    """编码前门禁 — 强制完成技术栈预研。"""

    CHECKLIST_FILENAME = "PRE_CODE_CHECKLIST.md"

    def generate_checklist(
        self,
        project_dir: Path,
        frontend: str = "",
        backend: str = "",
    ) -> Path:
        """生成 .super-dev/PRE_CODE_CHECKLIST.md。

        Returns:
            Path to the generated checklist.
        """
        superdev_dir = project_dir / ".super-dev"
        superdev_dir.mkdir(parents=True, exist_ok=True)
        checklist_path = superdev_dir / self.CHECKLIST_FILENAME

        content = self._build_checklist(frontend=frontend, backend=backend)
        checklist_path.write_text(content, encoding="utf-8")
        return checklist_path

    def check_completion(self, project_dir: Path) -> tuple[bool, list[str]]:
        """检查 checklist 是否完成（所有 [ ] 变为 [x]）。

        Returns:
            (all_complete, list_of_incomplete_items)
        """
        checklist_path = project_dir / ".super-dev" / self.CHECKLIST_FILENAME
        if not checklist_path.exists():
            return False, ["PRE_CODE_CHECKLIST.md does not exist"]

        try:
            text = checklist_path.read_text(encoding="utf-8")
        except OSError:
            return False, ["Cannot read PRE_CODE_CHECKLIST.md"]

        incomplete: list[str] = []
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("- [ ]"):
                item_text = stripped[5:].strip()
                incomplete.append(item_text)

        return len(incomplete) == 0, incomplete

    # ------------------------------------------------------------------
    # internals
    # ------------------------------------------------------------------

    def _build_checklist(self, *, frontend: str, backend: str) -> str:
        items: list[str] = [
            "# Pre-Code Checklist",
            "",
            "> Auto-generated by Super Dev enforcement.",
            "> Complete ALL items before writing implementation code.",
            "> Mark each item with [x] when done.",
            "",
            "## Architecture Confirmation",
            "",
            "- [ ] Read `output/*-architecture.md` and confirm API routes / data model",
            "- [ ] Read `output/*-prd.md` and confirm functional scope",
            "",
            "## UI/UX Confirmation",
            "",
            "- [ ] Read `output/*-uiux.md` and confirm icon library",
            "- [ ] Declare the component library being used (e.g. shadcn/ui, MUI, Ant)",
            "- [ ] Confirm typography system and design tokens are defined",
            "",
            "## Tech Stack Verification",
            "",
        ]

        if frontend in ("next", "nextjs", "next.js"):
            items.extend(
                [
                    "- [ ] Confirm App Router (not Pages Router) in `next.config.ts`",
                    "- [ ] Verify `tsconfig.json` path aliases match architecture doc",
                ]
            )
        elif frontend in ("vite", "react"):
            items.extend(
                [
                    "- [ ] Verify `vite.config.ts` settings match architecture doc",
                ]
            )
        elif frontend in ("vue", "nuxt"):
            items.extend(
                [
                    "- [ ] Verify `nuxt.config.ts` or `vite.config.ts` match architecture doc",
                ]
            )
        else:
            items.extend(
                [
                    "- [ ] Verify framework config file matches architecture doc",
                ]
            )

        if backend:
            items.extend(
                [
                    f"- [ ] Confirm backend framework ({backend}) entry point and structure",
                ]
            )

        items.extend(
            [
                "",
                "## Spec Alignment",
                "",
                "- [ ] Read `.super-dev/changes/*/tasks.md` for current task list",
                "- [ ] Confirm implementation order: SHALL/MUST first, then SHOULD, then MAY",
                "",
            ]
        )

        return "\n".join(items) + "\n"
