#!/bin/bash
# Super Dev Runtime Validation
# Auto-generated by super-dev enforce install

set -euo pipefail

ERRORS=0

# Helper: find existing source dirs
SRC_DIRS=""
for d in src/ app/ components/ pages/ lib/; do
  [ -d "$d" ] && SRC_DIRS="$SRC_DIRS $d"
done

if [ -z "$SRC_DIRS" ]; then
  echo "No source directories found — skipping validation."
  exit 0
fi

# ------------------------------------------------------------------
# Check 1: No emoji characters used as functional icons in source
# ------------------------------------------------------------------
echo "Checking for emoji in source files..."
EMOJI_FILES=$(grep -rn '[\x{1F300}-\x{1FAFF}\x{2600}-\x{27BF}]' --include='*.tsx' --include='*.ts' --include='*.jsx' --include='*.js' --include='*.vue' --include='*.svelte' $SRC_DIRS 2>/dev/null || true)
if [ -n "$EMOJI_FILES" ]; then
  echo "FAIL: Emoji found in source files:"
  echo "$EMOJI_FILES" | head -10
  ERRORS=$((ERRORS + 1))
fi

# ------------------------------------------------------------------
# Check 2: Icon library import consistency
# ------------------------------------------------------------------
echo "Checking icon library usage..."
WRONG_ICONS=$(grep -rn "from ['\"]react-icons" --include='*.tsx' --include='*.ts' --include='*.jsx' $SRC_DIRS 2>/dev/null || true)
if [ -n "$WRONG_ICONS" ]; then
  echo "FAIL: Found react-icons imports — use lucide-react instead:"
  echo "$WRONG_ICONS" | head -10
  ERRORS=$((ERRORS + 1))
fi

# ------------------------------------------------------------------
# Check 3: No hardcoded color values outside theme/config files
# ------------------------------------------------------------------
echo "Checking for hardcoded colors..."
HARDCODED_COLORS=$(grep -rn '#[0-9a-fA-F]\{3,8\}' --include='*.tsx' --include='*.jsx' --include='*.vue' --include='*.svelte' $SRC_DIRS 2>/dev/null | grep -v 'theme\|config\|tailwind\|token\|color' | grep -v '\.test\.' | grep -v 'node_modules' || true)
if [ -n "$HARDCODED_COLORS" ]; then
  echo "WARN: Potential hardcoded colors (review manually):"
  echo "$HARDCODED_COLORS" | head -10
  # Hardcoded colors are a warning, not a blocking error
fi

# ------------------------------------------------------------------
# Check 5: No console.log / console.error left in production code
# ------------------------------------------------------------------
echo "Checking for console.log/error statements..."
CONSOLE_STMTS=$(grep -rn 'console\.\(log\|error\|warn\|debug\)' --include='*.tsx' --include='*.ts' --include='*.jsx' --include='*.js' $SRC_DIRS 2>/dev/null | grep -v '\.test\.' | grep -v '\.spec\.' | grep -v 'node_modules' | grep -v '__tests__' || true)
if [ -n "$CONSOLE_STMTS" ]; then
  echo "FAIL: console.log/error found in production code:"
  echo "$CONSOLE_STMTS" | head -10
  ERRORS=$((ERRORS + 1))
fi

# ------------------------------------------------------------------
# Check 6: No hardcoded localhost URLs
# ------------------------------------------------------------------
echo "Checking for hardcoded localhost URLs..."
LOCALHOST_URLS=$(grep -rn 'http://localhost\|http://127\.0\.0\.1\|https://localhost' --include='*.tsx' --include='*.ts' --include='*.jsx' --include='*.js' --include='*.json' $SRC_DIRS 2>/dev/null | grep -v '\.test\.' | grep -v '\.spec\.' | grep -v 'node_modules' | grep -v '\.env' || true)
if [ -n "$LOCALHOST_URLS" ]; then
  echo "FAIL: Hardcoded localhost URLs found (use env vars instead):"
  echo "$LOCALHOST_URLS" | head -10
  ERRORS=$((ERRORS + 1))
fi

# ------------------------------------------------------------------
# Check 7: TODO / FIXME / HACK comments (warning only)
# ------------------------------------------------------------------
echo "Checking for TODO/FIXME/HACK comments..."
TODO_COMMENTS=$(grep -rn 'TODO\|FIXME\|HACK\|XXX' --include='*.tsx' --include='*.ts' --include='*.jsx' --include='*.js' --include='*.py' $SRC_DIRS 2>/dev/null | grep -v 'node_modules' || true)
if [ -n "$TODO_COMMENTS" ]; then
  TODO_COUNT=$(echo "$TODO_COMMENTS" | wc -l | tr -d " ")
  echo "WARN: $TODO_COUNT TODO/FIXME/HACK comment(s) found (review recommended):"
  echo "$TODO_COMMENTS" | head -5
  # Warning only — does not increment ERRORS
fi

# ------------------------------------------------------------------
# Check 8: Files larger than 500 lines (suggest splitting)
# ------------------------------------------------------------------
echo "Checking for oversized files..."
LARGE_FILES=$(find $SRC_DIRS -type f \( -name '*.tsx' -o -name '*.ts' -o -name '*.jsx' -o -name '*.js' \) 2>/dev/null | while read f; do   lines=$(wc -l < "$f" 2>/dev/null || echo 0);   [ "$lines" -gt 500 ] && echo "$f ($lines lines)"; done || true)
if [ -n "$LARGE_FILES" ]; then
  echo "WARN: Files exceeding 500 lines (consider splitting):"
  echo "$LARGE_FILES"
  # Warning only — does not increment ERRORS
fi

# ------------------------------------------------------------------
# Check 9: package.json must have build and lint scripts
# ------------------------------------------------------------------
if [ -f "package.json" ]; then
  echo "Checking package.json scripts..."
  if ! grep -q '"build"' package.json 2>/dev/null; then
    echo "FAIL: package.json missing \"build\" script"
    ERRORS=$((ERRORS + 1))
  fi
  if ! grep -q '"lint"' package.json 2>/dev/null; then
    echo "FAIL: package.json missing \"lint\" script"
    ERRORS=$((ERRORS + 1))
  fi
fi

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------
echo ""
if [ $ERRORS -eq 0 ]; then
  echo "All Super Dev validation checks passed"
  exit 0
else
  echo "$ERRORS Super Dev validation check(s) failed"
  exit 2
fi
